force-app/main/default/objects/Venda__c/Venda__c.object-meta.xml
<CustomObject>
    <label>Venda</label>
    <nameField>
        <label>Venda Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Venda__c/fields/Comissao__c.field-meta.xml
<CustomField>
    <fullName>Comissao__c</fullName>
    <label>Comissao</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Venda__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendente, Fechada, Cancelada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Venda__c/fields/Valor__c.field-meta.xml
<CustomField>
    <fullName>Valor__c</fullName>
    <label>Valor</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/VendasController.cls
public with sharing class VendasController {
    
    // Essa é a estrutura que o nosso Front-end vai receber
    public class ResumoVenda {
        @AuraEnabled public String status;
        @AuraEnabled public Integer totalVendas;
        @AuraEnabled public Decimal faturamento;
        @AuraEnabled public Decimal comissoes;
    }

    // A anotação @AuraEnabled(cacheable=true) é obrigatória para o LWC enxergar o método
    @AuraEnabled(cacheable=true)
    public static List<ResumoVenda> getResumoVendas() {
        List<ResumoVenda> listaResumo = new List<ResumoVenda>();
        
        // Rodamos a exata mesma query que você fez no terminal
        String query = 'SELECT Status__c, COUNT(Id) t, SUM(Valor__c) f, SUM(Comissao__c) c FROM Venda__c GROUP BY Status__c';
        
        for(AggregateResult ar : Database.query(query)) {
            ResumoVenda resumo = new ResumoVenda();
            resumo.status = (String)ar.get('Status__c');
            resumo.totalVendas = (Integer)ar.get('t');
            resumo.faturamento = (Decimal)ar.get('f');
            // Como a comissão pode ser nula em canceladas, fazemos um tratamento ternário
            resumo.comissoes = ar.get('c') != null ? (Decimal)ar.get('c') : 0; 
            
            listaResumo.add(resumo);
        }
        
        return listaResumo;
    }
}